[project]
name = "aerodynamics-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.1",
    "numpy>=2.3.4",
    "pygithub>=2.8.1",
    "pykml>=0.2.0",
    "pyqtgraph>=0.13.7",
    "pyside6>=6.10.0",
    "shapely>=2.1.2",
    "tomli-w>=1.2.0",
]
